modLoader="javafml" #mandatory

loaderVersion="[43,)"
license="GNU GPLv3"
state="WIP"
[[mods]] #mandatory
modId="flint" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Xuul's HEAT" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="Xuul" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod the changes the early game of minecraft
'''